apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-client-job
spec:
  template:
    metadata:
      name: mysql-client-job
    spec:
      containers:
      - image: atjapan2015/mysql-client-initdb:8.0.12
        name: mysql-client-job
        args:
        - /bin/bash
        - -c
        - sleep 15; /bin/bash /tmp/init.sh; exit
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE              
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
      restartPolicy: Never
