apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: V2VsY29tZV8xMjM= #Welcome_123
  MYSQL_DATABASE: d29ybGQy #world2
  MYSQL_USER: cm9vdA== #root
  MYSQL_PASSWORD: V2VsY29tZV8xMjM= #Welcome_123
