apiVersion: v1
kind: Service
metadata:
  name: mysql8012
spec:
  ports:
  - port: 3306
  selector:
    app: mysql8012
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: V2VsY29tZV8xMjM= #Welcome_123
  MYSQL_DATABASE: d29ybGQy #world2
  MYSQL_USER: cm9vdA== #root
  MYSQL_PASSWORD: V2VsY29tZV8xMjM= #Welcome_123
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /u01/data/var/lib/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql8012
spec:
  selector:
    matchLabels:
      app: mysql8012
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql8012
    spec:
      containers:
#      - image: mysql:8.0.12
      - image: mysql:5.7.21      
        name: mysql8012
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE              
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql8012
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim                            
